# Generated by Django 3.2.8 on 2021-10-11 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chatttt', '0002_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='username',
            new_name='user',
        ),
    ]
