# Generated by Django 3.2.8 on 2021-10-11 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chatttt', '0003_rename_username_friends_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='user',
            new_name='username',
        ),
    ]
