# Generated by Django 3.2.8 on 2021-10-12 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chatttt', '0007_friends'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
