# Generated by Django 3.2.8 on 2021-10-12 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chatttt', '0011_auto_20211012_0926'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
